In [1]:
 #np.array

import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#2D and 3D array

b = np.array([[1,2,3] , [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2] , [3,4]] , [[5,6] , [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
#dtype
np.array([1,2,3] , dtype = float)

array([1., 2., 3.])

In [5]:
np.arange(1,11 ,2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(16).reshape(2 , 2 , 2 , 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
#np.ones and np.zeroes
np.ones((3 , 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#np.random

np.random.random((3,4))

array([[0.44653828, 0.96652634, 0.41744836, 0.34445488],
       [0.02257927, 0.7970766 , 0.53944591, 0.16930293],
       [0.02148256, 0.16772631, 0.00913327, 0.18179   ]])

In [13]:
#np.linespace
np.linspace(-10 , 10 , 10 , dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [14]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Array attributes

a1 = np.arange(10 , dtype = np.int32)
a2 = np.arange(12 , dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
a3.ndim

3

In [20]:
#shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [22]:
#itemsize
a3.itemsize

8

In [23]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [24]:
#Changing Datatype
#astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [25]:
#Array operations

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12 , 24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
#Scalar operation
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [27]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
#relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [30]:
#Array Functions

a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1

array([[89., 51., 25.],
       [90., 79., 61.],
       [38., 82., 82.]])

In [31]:
#max / min / sum / prod
# 0 -> col and 1 -> row
np.prod(a1 , axis = 0)

array([304380., 330378., 125050.])

In [32]:
#mean , median , std / var
np.var(a1 , axis = 1)

array([690.66666667, 142.88888889, 430.22222222])

In [33]:
#trigonometric functions

np.sin(a1)

array([[ 0.86006941,  0.67022918, -0.13235175],
       [ 0.89399666, -0.44411267, -0.96611777],
       [ 0.29636858,  0.31322878,  0.31322878]])

In [35]:
#dot product

a2 = np.arange(12).reshape(3 , 4)
a3 = np.arange(12 , 24).reshape(4,3)

a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [36]:
#log and exponents 
np.exp(a1)

array([[4.48961282e+38, 1.40934908e+22, 7.20048993e+10],
       [1.22040329e+39, 2.03828107e+34, 3.10429794e+26],
       [3.18559318e+16, 4.09399696e+35, 4.09399696e+35]])

In [37]:
# round / floor/ ceil
np.ceil(np.random.random((2,3)) * 100)

array([[87., 75., 94.],
       [38., 85., 85.]])

In [44]:
#indexing and slicing

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a2[1 , 0]

np.int64(4)

In [45]:
a3[1, 0,1]

np.int64(5)

In [46]:
a3[1, 1,0]

np.int64(6)

In [49]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a1[2 : 5 : 2]

array([2, 4])

In [50]:
a2[0:2,1::2]


array([[1, 3],
       [5, 7]])

In [52]:
a2[::2 , 1 :: 2]

array([[ 1,  3],
       [ 9, 11]])

In [54]:
a2[1 , ::3]

array([4, 7])

In [56]:
a2[0,:]

array([0, 1, 2, 3])

In [58]:
a2[:,2]


array([ 2,  6, 10])

In [59]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [61]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
a3[::2,0,::2]


array([[ 0,  2],
       [18, 20]])

In [63]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [64]:
a3[0,1,:]

array([3, 4, 5])

In [66]:
# iterating

a1

for i in a1 : 
    print(i)

0
1
2
3
4
5
6
7
8
9


In [67]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
for i in a2 :
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [69]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
for i in a3 : 
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [71]:
for i in np.nditer(a3) : 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [72]:
#reshap
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [73]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [75]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [76]:
#Stacking

#horizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12 , 24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [78]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])